server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: service-gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: service-books-id
          uri: lb://service-books
          predicates:
            Path=/books/**
          filters:
            - AuthFilter
        - id: service-investor-id
          uri: lb://service-investor
          predicates:
            Path=/investor/**
        - id: service-borrower-id
          uri: lb://service-borrower
          predicates:
            Path=/borrower/**
        - id: service-disbursement-id
          uri: lb://service-disbursement
          predicates:
            Path=/disbursement/**
        - id: service-amortization-id
          uri: lb://service-amortization
          predicates:
            Path=/amortization/**
        - id: service-repayment-id
          uri: lb://service-repayment
          predicates:
            Path=/repayment/**
        - id: service-distribution-id
          uri: lb://service-distribution
          predicates:
            Path=/distribution/**
        - id: service-foreclosure-id
          uri: lb://service-foreclosure
          predicates:
            Path=/foreclosure/**
        - id: service-users-sign-in
          uri: lb://service-users
          predicates:
            - Path=/users/signIn,/users/signUp
  zipkin:
    baseUrl: http://127.0.0.1:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
