server:
  port: 0
  servlet:
    context-path: /batch

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  application.name: service-batch
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lendenlms
    jdbc-url: jdbc:postgresql://localhost:5432/lendenlms
    username: service_batch
    password: srv-bat
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
#   mono:
#     datasource:
#       driverClassName: org.postgresql.Driver
#       password: JNbrNhdxy_WThjkY
#       url: jdbc:postgresql://lenden-club.c60xechvrdpu.ap-south-1.rds.amazonaws.com:5432/lendenexo
#       username: read_exolendenite
  users:
    datasource:
      driverClassName: org.postgresql.Driver
      password: srv-usrs
      url: jdbc:postgresql://localhost:5432/lendenlms
      username: service_users
  partner:
    datasource:
      driverClassName: org.postgresql.Driver
      password: srv-part
      url: jdbc:postgresql://localhost:5432/lendenlms
      username: service_partner
  investor:
    datasource:
      driverClassName: org.postgresql.Driver
      password: srv-invest
      url: jdbc:postgresql://localhost:5432/lendenlms
      username: service_investor
  borrower:
    datasource:
      driverClassName: org.postgresql.Driver
      password: srv-borrow
      url: jdbc:postgresql://localhost:5432/lendenlms
      username: service_borrower
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  batch:
    initialize-schema: always
    schema: classpath:org/springframework/batch/core/schema-postgresql.sql
    job:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
