server:
  port: 0
  servlet:
    context-path: /mails

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      function:
        definition: listenMessages
      bindings:
        listenMessages-in-0.destination: mails
      kafka:
        bindings:
          listenMessages-in-0.destination: mails
            consumer:
              configuration:
                value:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
      binder:
        brokers: localhost:9092

#kafka.bootstrapAddress: localhost:9092
